### ISSUE TITLE
Build Error, File Not Found Exception

### ISSUE THREAD

**Issue by hartkemd** [jellyfishfingers/EmailTemplateGenerator#3]
Hello,

I want to help work on this project.

First, I was trying to see the code in action. I cloned the repo in Visual Studio, however I could not build the solution. I got the error: "NETSDK1004 Assets file 'EmailTemplateGenerator\obj\project.assets.json' not found. Run a NuGet package restore to generate this file."

I ran a NuGet package restore, but now I'm getting the exception: "System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, or one of its dependencies. The system cannot find the file specified.'" Any ideas on how this can be resolved? Were you able to build the solution and run the app?

Thank you.

**Comment by jellyfishfingers** [comment]
Thanks for the feedback... I'll try to do any push request with newer code

**Comment by jellyfishfingers** [comment]
Hi @hartkemd , I just pushed some code. I'm able to build the project, both in Visual Studio Code and Visual Studio (Community).

**Comment by hartkemd** [comment]
I'm still having problems, but I think pull request #4 will fix the issues.
